---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nop-crossplane-io-v1alpha1-nopresource
  failurePolicy: Fail
  name: nopresources.nop.crossplane.io
  rules:
  - apiGroups:
    - nop.crossplane.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nopresources
  sideEffects: None
