apiVersion: sample.nop.crossplane.io/v1alpha1
kind: NopResource
metadata:
  name: example
spec:
  forProvider:
    conditionAfter:
      - conditionType: "Ready"
        conditionStatus: "False"
        time: "5s"
      - conditionType: "Ready"
        conditionStatus: "True"
        time: "10s"
      - conditionType: "Synced"
        conditionStatus: "False"
        time: "15s"
      - conditionType: "Synced"
        conditionStatus: "True"
        time: "20s"