apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-nop
  annotations:
    company: Crossplane
    maintainer: Crossplane Maintainers <info@crossplane.io>
    source: github.com/crossplane-contrib/provider-nop
    license: Apache-2.0
    descriptionShort: |
      The nop Crossplane provider enables testing managed resources.
    description: |
      The nop Crossplane provider adds support for managing resources that
      reflect the conditions from the spec in their status. This can be useful
      for testing managing managed resources in larger systems.
    readme: |
      The nop Crossplane provider enables testing managed resources.
